<a href="https://colab.research.google.com/github/Aminsfwt/Clean-Education-Indicators-using-pandas/blob/main/Education_Indicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tableau project on education story in this century using data from world bank**

first download Education indecators from world bank in this link:
https://data.worldbank.org/indicator

#Import pandas library

In [1]:
import pandas as pd

#First load first dataset Education Indecators

In [2]:
#load data
df = pd.read_csv("Education_Indecators.csv")

print(df.head())

  Country Name Country Code  \
0  Afghanistan          AFG
1  Afghanistan          AFG
2  Afghanistan          AFG
3  Afghanistan          AFG
4  Afghanistan          AFG

                                      Indicator Name     Indicator Code  \
0      Population ages 15-64 (% of total population)  SP.POP.1564.TO.ZS
1       Population ages 0-14 (% of total population)  SP.POP.0014.TO.ZS
2  Unemployment, total (% of total labor force) (...     SL.UEM.TOTL.ZS
3  Unemployment, male (% of male labor force) (mo...  SL.UEM.TOTL.MA.ZS
4  Unemployment, female (% of female labor force)...  SL.UEM.TOTL.FE.ZS

        1960       1961       1962       1963       1964       1965  ...  \
0  55.229884  55.162055  55.094352  54.988991  54.832669  54.616091  ...
1  41.946754  42.028588  42.112814  42.235952  42.409539  42.642237  ...
2        NaN        NaN        NaN        NaN        NaN        NaN  ...
3        NaN        NaN        NaN        NaN        NaN        NaN  ...
4        NaN        NaN        NaN        NaN        NaN        NaN  ...

        2015       2016       2017       2018       2019       2020  \
0  51.383968  51.843054  52.275658  52.673272  53.047015  53.405162
1  46.259337  45.801449  45.364605  44.959607  44.576832  44.224104
2   9.052000  10.133000  11.184000  11.196000  11.185000  11.710000
3   8.401000   9.399000  10.363000  10.198000  10.031000  10.456000
4  11.611000  12.834000  14.018000  14.783000  15.549000  16.778000

        2021       2022       2023       2024
0  53.739325  54.065016  54.396259  54.711524
1  43.908125  43.579841  43.226204  42.887506
2  11.994000  14.100000  13.991000  13.295000
3  10.911000  13.168000  13.066000  12.394000
4  16.945000  26.742000  26.570000  25.636000

[5 rows x 69 columns]

#Drop Country Code and Indicator Code columns

In [4]:
df = df.drop(columns=['Country Code', 'Indicator Code'])
print(df.head())

  Country Name                                     Indicator Name       1960  \
0  Afghanistan      Population ages 15-64 (% of total population)  55.229884
1  Afghanistan       Population ages 0-14 (% of total population)  41.946754
2  Afghanistan  Unemployment, total (% of total labor force) (...        NaN
3  Afghanistan  Unemployment, male (% of male labor force) (mo...        NaN
4  Afghanistan  Unemployment, female (% of female labor force)...        NaN

        1961       1962       1963       1964       1965       1966  \
0  55.162055  55.094352  54.988991  54.832669  54.616091  54.362958
1  42.028588  42.112814  42.235952  42.409539  42.642237  42.910286
2        NaN        NaN        NaN        NaN        NaN        NaN
3        NaN        NaN        NaN        NaN        NaN        NaN
4        NaN        NaN        NaN        NaN        NaN        NaN

        1967  ...       2015       2016       2017       2018       2019  \
0  54.114336  ...  51.383968  51.843054  52.275658  52.673272  53.047015
1  43.172422  ...  46.259337  45.801449  45.364605  44.959607  44.576832
2        NaN  ...   9.052000  10.133000  11.184000  11.196000  11.185000
3        NaN  ...   8.401000   9.399000  10.363000  10.198000  10.031000
4        NaN  ...  11.611000  12.834000  14.018000  14.783000  15.549000

        2020       2021       2022       2023       2024
0  53.405162  53.739325  54.065016  54.396259  54.711524
1  44.224104  43.908125  43.579841  43.226204  42.887506
2  11.710000  11.994000  14.100000  13.991000  13.295000
3  10.456000  10.911000  13.168000  13.066000  12.394000
4  16.778000  16.945000  26.742000  26.570000  25.636000

[5 rows x 67 columns]

#clean columns by lowercase names and replace spaces by undescore

In [5]:
#Clean up column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.head()

,country_name,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,Population ages 15-64 (% of total population),55.229884,55.162055,55.094352,54.988991,54.832669,54.616091,54.362958,54.114336,...,51.383968,51.843054,52.275658,52.673272,53.047015,53.405162,53.739325,54.065016,54.396259,54.711524
1,Afghanistan,Population ages 0-14 (% of total population),41.946754,42.028588,42.112814,42.235952,42.409539,42.642237,42.910286,43.172422,...,46.259337,45.801449,45.364605,44.959607,44.576832,44.224104,43.908125,43.579841,43.226204,42.887506
2,Afghanistan,"Unemployment, total (% of total labor force) (...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.052000,10.133000,11.184000,11.196000,11.185000,11.710000,11.994000,14.100000,13.991000,13.295000
3,Afghanistan,"Unemployment, male (% of male labor force) (mo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.401000,9.399000,10.363000,10.198000,10.031000,10.456000,10.911000,13.168000,13.066000,12.394000
4,Afghanistan,"Unemployment, female (% of female labor force)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.611000,12.834000,14.018000,14.783000,15.549000,16.778000,16.945000,26.742000,26.570000,25.636000

#Take only years from 2000 to 2024 from the dataset and unpevot the dataset to make only column for the years and column for the indicators values

In [ ]:

# Identify year columns from 2000 to 2024
year_cols = [str(y) for y in range(2000, 2025) if str(y) in df.columns]

# Melt the dataset to convert years columns to one column
df_long = df.melt(
    id_vars=['country_name', 'indicator_name'],
    value_vars=year_cols,                       # columns to unpivot
    var_name='year',                            # new column name for years
    value_name='indicator_value'                # new column name for values
)

df_long.head()

#Convert year to integer and drop missing values

In [8]:
df_long['year'] = df_long['year'].astype(int)
df_long.dropna(subset=['indicator_value'], inplace=True)
df_long.head()

,country_name,indicator_name,year,indicator_value
0,Afghanistan,Population ages 15-64 (% of total population),2000,47.71310
1,Afghanistan,Population ages 0-14 (% of total population),2000,50.02493
2,Afghanistan,"Unemployment, total (% of total labor force) (...",2000,7.93500
3,Afghanistan,"Unemployment, male (% of male labor force) (mo...",2000,7.46300
4,Afghanistan,"Unemployment, female (% of female labor force)...",2000,10.48300

In [9]:
#remove impossible or extreme values
df_long.loc[df_long['indicator_value'] < 0, 'indicator_value'] = None
df_long.loc[df_long['indicator_value'] > 100, 'indicator_value'] = 100

#Save the cleaned and reshaped data

In [10]:
df_long.to_csv("Education_Indicators.csv", index=False)